version: "3.9"


services:
  api:
    build:
      context: .
    image: andrewisaev/skypro_aisaev_app
    ports:
      - 80:80
    volumes:
      - ./default_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    image: andrewisaev/skypro_aisaev_app
    volumes:
      - ./default_config.py:/code/default_config.py
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: my_app
      POSTGRES_PASSWORD: my_app_password
      POSTGRES_DB: my_app
    volumes:
      - ./pg_data:/var/lib/pastgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5